### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by LucasPilla** [Jaco7Fourie/BrickWall#1]
- Add requirements.txt
You should add a requirements.txt so becomes easier to install all dependencies for you program.
If you have a file requirements.txt:
 ```
cairosvg==2.4.2
depq==1.5.5
drawsvg==1.7.0
pygame_gui==0.5.7
pygame==1.9.6
```
I could easily run `pip install -r requirements.txt`.

- Change display size
The program display width is bigger than my  computer screen width, maybe you should make it smaller or find a way that it works for any screen size.

By the way, this project is amazing ;)

**Comment by Jaco7Fourie** [comment]
Thanks for the suggestions. The requirements.txt is easy, I will add that next weekend when I can work on this again. The display resolution is a bit harder. I have experimented with this before and you will notice that the display size is actually a parameter for the main app. However, making this an arbitrary setting makes the GUI look ugly (even more than it already is :) ) for most sizes. I'll experiment some more with this over the weekend.

**Comment by Jaco7Fourie** [comment]
The GUI will now detect the screen resolution and resize the screen to an appropriate size.  I also added a requirements.txt for easier installation. Note the extra dependency of the screeninfo library that is now required.
